var json = {
	"contact1": {
		"fname": 		 ["First Name:", "Travis"],
		"lname": 		 ["Last Name:", "Pochintesta"],
		"address": 		 ["Address:", "2217 Delaney Ave. Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)230-6001"],
		"email":		 ["Email:", "travisp@fullsail.edu"],
		"gender": 	   	 ["Gender:", "Male"],
		"title":		 ["Title:", "Mr."],
		"friend":		 ["Friend:", "No"],
		"family":	   	 ["Family:", "Yes"],
		"school":  		 ["School:", "No"],
		"work":			 ["Work:", "No"],
		"acquaintance":  ["Acquaintance:", "No"],
		"birthday":		 ["Birthday:", "1977-12-17"],
		"bestyrating":	 ["Besty Rating:", "100"],
		"notes":		 ["Notes:", "VFW"]		
	},
	"contact2": {
		"fname": 		 ["First Name:", "Jana"],
		"lname": 		 ["Last Name:", "Pochintesta"],
		"address": 		 ["Address:", "2217 Delaney Ave. Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)617-7875"],
		"email":		 ["Email:", "jnewkerk@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Mrs."],
		"friend":		 ["Friend:","No"],
		"family":	   	 ["Family:", "Yes"],
		"school":  		 ["School:","No"],
		"work":			 ["Work:","No"],
		"acquaintance":  ["Acquaintance:","No"],
		"birthday":		 ["Birthday:", "1974-04-09"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Wife"]		
	},
	"contact3": {
		"fname": 		 ["First Name:", "Kiet"],
		"lname": 		 ["Last Name:", "Pochintesta"],
		"address": 		 ["Address:", "2217 Delaney Ave. Orl, FL 32806"],
		"phone":		 ["Phone:", "(407)738-8817"],
		"email":		 ["Email:", "kgp2001@gmail.com"],
		"gender": 	   	 ["Gender:", "Female"],
		"title":		 ["Title:", "Ms."],
		"friend":		 ["Friend:","No"],
		"family":	   	 ["Family:", "Yes"],
		"school":  		 ["School:","No"],
		"work":			 ["Work:","No"],
		"acquaintance":  ["Acquaintance:","No"],
		"birthday":		 ["Birthday:", "2001-12-20"],
		"bestyrating":	 ["Besty Rating:","100"],
		"notes":		 ["Notes:", "Daughter"]		
	},
}